### ISSUE TITLE
Can I use this? https://goo.gl/4uKPSf

### ISSUE THREAD

**Issue by lunalik** [Plailect/Guide#1202]
I was just wondering if you are fine with me sharing this compact version of your 3ds.guide soundhax tutorial I've made https://goo.gl/4uKPSf (I've credited you of course). I also am planning to use it in a video tutorial (which once again, I will obviously credit you in). Please respond soon. Thank you.

**Comment by Plailect** [comment]
This is just the exact same thing but less detailed and put on one page....

Video guides are looked down upon because they become *very* quickly outdated after their upload.

That's just my opinion. [You do not need my permission to use or modify any part of the guide.](https://github.com/Plailect/Guide/blob/master/LICENSE.txt)

**Comment by lunalik** [comment]
The main reason I made it is because on 3ds.guide you have to go around downloading files and making folders for a good portion of the guide, and I understand it's to get the latest release of everything, so I'm not criticizing, but having an all in one package is more convenient, and I will try my best to constantly update it, but I do agree that it will get outdated if the method changes. Thanks for responding anyways.
