### ISSUE TITLE
Themely?

### ISSUE THREAD

**Issue by lunalik** [Plailect/Guide#1263]

**Comment by lunalik** [comment]
I heard that there was something wrong with the new version of Themely, but what was it? Was it really serious enough to remove it from the guide?

**Comment by nl255** [comment]
Yes, not only did it go closed source but the author of Themely after hearing about the unbanmii incident said he said that it was a smart idea to steal seeds and other info.  Since it also has an auto-updater which will update to the latest closed source, and potentially malware containing version it is not safe to use.  For those who still want to use it they should manually install release v1.3.1-i0 or newer from https://github.com/ihaveamac/Themely/releases as that fork by ihavamac will remain open source and v1.3.1-i0 changed the updater to install the latest release of the ihavamac fork.  Do NOT install anything older than v1.3.1-i0 from that release page.

**Comment by Aluminite** [comment]
Has anyone absolutely confirmed that the newest Themely release does or does not contain malware (for example, looking through the data it is sending)?

**Comment by nl255** [comment]
No, and without the source code doing so is impractical as there are plenty of ways to make it harder to detect which means short of going through the entire disassembly instruction by instruction (which would take forever and would need to be repeated with each new future version) there is no real way to tell if it is just "laying low" at the moment.  Especially given the comments that the developer of Themely made about the unbanmii incident and there is no reason for it to go closed source except to hide something like that nobody is going to go to all that trouble of doing a full disassembly and line by line analysis especially when there is a perfectly good fork that will remain open source as well as someone else (astronautlevel) working on a completely new replacement.

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/ba5c7aae2391877a2a2b14d8b526a56a99176582
