### ISSUE TITLE
Transfering NNID question

### ISSUE THREAD

**Issue by Ninjistix** [Plailect/Guide#1296]
After following the guide, the NNID moved from Source 3DS to Target 3DS, doing a restore of the backup from Godmode9 the NNID shows up on both systems, What will happen if I try to trasnfer back the NNID from the Target to the Source?

**Comment by Ninjistix** [comment]
NID*

**Comment by Plailect** [comment]
You should restore the NAND *after* doing the steps to re-link the NNID (such as transfering back). Since you already have restored, you should [remove the NNID](https://3ds.guide/troubleshooting#rm_nnid) from the source 3DS before transfering. 

This will format the target 3DS (but it will not uninstall boot9strap).

**Comment by Ninjistix** [comment]
@Plailect  Didn't want to open a new topic, But I'm having an issue with transferring the NNID back to the source 3DS, I removed the NNID as suggested before, once the transfer starts around step 2/5 of transfering builtin software, I get a transfer local wireless error and error 

**Source 3DS (transferring too)**
![537fcb5f-c68e-4cfd-9dc9-fa5eecd2f206](https://user-images.githubusercontent.com/12572974/29548508-6881fc2a-86cf-11e7-8015-421d73c61109.JPG)

**Target 3DS (transferring from)**
![a5e47b38-7562-46b4-9f82-c4b1d3c6a0e3](https://user-images.githubusercontent.com/12572974/29548510-6c123ff8-86cf-11e7-9efb-6aee0a320031.JPG)
