### ISSUE TITLE
Why not use safeb9sinstaller.bin as your arm9loaderhax.bin in a9lh-to-b9s?

### ISSUE THREAD

**Issue by jason0597** [Plailect/Guide#1411]
In the a9lh-to-b9s guide, the current process involves manually updating to luma 7.0.5 to ensure the user has access to luma's chainloader menu, so that they can run safeb9sinstaller.bin

However, why not simply rename safeb9sinstaller.bin to arm9loaderhax.bin, and therefore speed up the process? 
I was told that this wouldn't be a good idea for users who do not have an SD card who rely on ftpd for accessing their SD card, because if something were to go wrong (say they download the dev or ntr version of boot9strap and safeb9sinstaller refuses to install it for them), then they will not be able to boot into the home menu at all (to run ftpd), and they therefore it would be impossible for them to fix this. However this is inconsistent with another guide, as the update-b9s guide assumes that the user _does_ have an SD card reader (to resolve the argc = 0 error right after updating boot9strap from v1.0 to v1.3) 

Renaming safeb9sinstaller.bin to arm9loaderhax.bin would also fix another issue. Currently, if someone were to update from luma 6.6 to luma 7.0.5, it would bring them to the luma configuration menu on boot, and I've seen this quite often in the discord channel were people come in and say "help if i hold start on boot i go into luma config how do i fix".

**Comment by DarthJJAbrams** [comment]
The SD card reader requirement for Updating B9S is a lot more out of necessity, since it isn't possible to have two versions of boot.firm on the card at once. The only way to fix that would be to run godmode9 scripts that change it. It is possible to have both 7.0.5 and 8.1.1 on the card since they are named differently, so having speed sacrificed is a good tradeoff in my opinion.

It doesn't matter much which direction is taken though, while I would prefer the safety net of the current version this is better for the vast majority of users.

**Comment by jason0597** [comment]
In that case there should be disclaimers at the top linking to alternative guides for users with no SD card reader
