### ISSUE TITLE
R4i Gold 3DS no longer sold

### ISSUE THREAD

**Issue by SizzlinRoast** [Plailect/Guide#1461]
atleast on nds-card that is, but i think a small note should just reflect that to people. much thank

**Comment by Mike15678** [comment]
From what I can tell, the r4i Gold 3DS RTS is still being sold, yet it is hidden on nds-card, meaning that you can still buy it through the link found in the guide, which is: http://www.nds-card.com/ProShow.asp?ProID=149
That's the only way (from what I can tell) in order to get access to its product page, which allows you to buy it.

**Comment by SizzlinRoast** [comment]
even if you get access to the product page, i have heard that they just ship the "plus" variant of the card instead which is preflashed
