### ISSUE TITLE
DSiWare method NNID

### ISSUE THREAD

**Issue by lootziedoodle** [Plailect/Guide#1470]
![image](https://user-images.githubusercontent.com/34919575/34416695-f5fcbc18-ebf4-11e7-8ba9-94a3e7bda7e0.png)
it should be noted that theres a gm9 script that removes the nnid from a 3ds without formatting it

**Comment by Mike15678** [comment]
After a system transfer, the NNID becomes linked with the target console, meaning if you try to format or use the GodMode9 script to remove the NNID from the target console, it’ll still be linked (with the target console) and remain “stuck”. The only way to transfer the NNID back and link it to the source console, is to call Nintendo or perform another system transfer after a week has elapsed since the first system transfer for a specific NNID.
With all of that being said, I don’t believe it’s appropriate to mention inside of the infobox that there is a GodMode9 script that can remove the NNID from the target console, as it’ll remain linked unless you follow one of the methods listed in the infobox.

**Comment by Plailect** [comment]
I agree with @Mike15678.
