### ISSUE TITLE
Comments on 9.2 update

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#171]
-- 4.x.x should not contain an option "+ 6.X.X-0 Cart Update then 6.X.X-0 MSET".  This never has any benefit over 4.X mset.
-- Attempting to follow this guide with 1.x or 2.x and getting the OTP won't work, because the user is told to skip to part 5, but part 5 includes a copying RedNAND step.  Because they skipped to part 5, they don't have a RedNAND.
-- This guide misses the case of 9.0-9.2 + low/no browser.  (Has it been confirmed that Ninjhax 2 doesn't work on such systems?)
-- Where the guide describes how to do a cart update, it needs to tell the user to delete any downloaded update first.  (Has it been confirmed that the usual method of deleting a downloaded update does a complete deletion and a cart update will not then try to use it?)
-- Is getting the OTP using the 2.1 method possible on 2.2?
Edit: "If you are between versions 9.0.0 and 9.8.0, you should follow this guide, but you can skip changing the date and time in the beginning." should say "If you are between versions 9.0.0 and 9.8.0, you should follow this guide, but you can skip changing the date and time and initializing savedata in the beginning".

**Comment by MelonGx** [comment]
9.0-9.2 with low/no browsers:
- One Chinese user failed on 9.2.0-4U, then succeeded on 9.2.0-4U -> 9.9.0-4U -> 9.2.0-20U.
- For whom wants to test them again: Cooking Mama provides 9.0.0E, Super Smash Bros. (Only a few versions) provides 9.2.0U, No 9.0.0-9.2.0J exist.

**Comment by MelonGx** [comment]
For 1.X and 2.0's shortcut, it should be:
- (1) Cubic Ninja OTP (and NAND backup for whom wants unpolluted ticket.db - later NAND backup will not give you an unpolluted ticket.db since installing CIA Sysupdater already installed an illegal ticket on it. FBI's delete ticket option can only disable those illegal tickets. It can't remove them from ticket.db even they're "deleted" which actually = disabled.)
- (2) Upgrade to 9.2.0-20
- (3) Do some preparations for directly going to Part 5 (actually it's only (1) 9.2.0-20 NAND backup without A9LH (2) Softwares and guide to boot HBL)
- (4) Go to Part 5 and ignore Section IV & V

**Comment by Plailect** [comment]
Edited.
