### ISSUE TITLE
url miss?

### ISSUE THREAD

**Issue by srwgin** [Plailect/Guide#179]
https://github.com/Plailect/Guide/wiki/9.2.0-Update-(Gateway-EmuNAND)
can not open this url

**Comment by Plailect** [comment]
Gateway support and info in the guide is coming soon.

**Comment by MelonGx** [comment]
This is a method for giving Devmode/PastaMode access on 7.X.X-(2 to 6) reported by a few Chinese users.
It should be:
- (1) Use GW URL to web-boot Launcher.dat on 7.X.X-(2 to 6)
- (2) Create GW EmuNAND and unlink them
- (3) Use BigBlueMenu.3DS to install 9.2.0-20 CIA on EmuNAND
- (4) Web-boot Launcher.dat on EmuNAND, then downgrade EmuNAND to 4.X
- (5) Convert GWDG EmuNAND 4.X into RedNAND (if not then it may cause a brick on injecting to the SysNAND)
- (6) Backup 7.X.X-(2 to 6) SysNAND for emergency, then inject 4.X RedNAND into SysNAND
- (7) Use Decrypt9 to dump CTRNAND partition
- (8) Mount CTRNAND with OSFmount, then defrag it (if not, Decrypt9 will get an error on dumping H&S because GW downgrade has messed up the CTRNAND)
- (9) After the defragment, inject CTRNAND back to SysNAND
- (10) Continue to 9.2.0 update guide for 4.X.X

D0k3 recommends using a 3rd party defrag program more than Windows bundled. But I forgot its name.
