### ISSUE TITLE
Error During Downgrade (Page 2)

### ISSUE THREAD

**Issue by Sorrento6** [Plailect/Guide#184]
Do I really have to update to 11 if I'm one of the few unlucky ones?????

**Comment by jaxrogers2** [comment]
Pretty much. That's why formatting the system before attempting the downgrade without a hardmod is recommended.

**Comment by Sorrento6** [comment]
Thanks.

**Comment by Sorrento6** [comment]
Do you think that there will ever be a resolution to this 11.0 debauchery?

**Comment by jaxrogers2** [comment]
Well, hardmods still work for now, but software only downgrading on 11.0 would be very difficult to implement. Svchax would have to be fixed, and not only that, the downgrader program would have to run very fast to beat the 11.0 title version installation check for every single title (since you only have a few frames to beat the check entirely). It would also have to be able to detect when a title install was blocked by the check so it would try again to reinstall the title because otherwise the downgrader would always partial if any title was blocked.

So overall, due to these issues, if software downgrading were even possible on 11.0, it would be more risky than downgrading via a hardmod, so that is why a 11.0 software downgrader is not currently being worked on.

**Comment by Sorrento6** [comment]
![20160612_171403](https://cloud.githubusercontent.com/assets/18752879/15993897/05aab3e4-30c2-11e6-8a80-fb7f663bf04b.jpg)

After finishing the guide, I open the hb launcher cia that has been installed and then I get the above message until it finally errors out and tells me to press start and exit. Any suggestions? Other CIA files loaded and opened fine including the Luma Update cia.

**Comment by nickthegamer5** [comment]
Are you connected to wifi?

**Comment by Sorrento6** [comment]
I believe so. I did a connection test and it was successful. Do you think
that doing a Luma update had snow effect on it?
On Jun 12, 2016 5:58 PM, "Nick" <notifications@github.com> wrote:
>
> Are you connected to wifi?
>
> > On Jun 12, 2016, at 5:24 PM, Sorrento6 <notifications@github.com>
wrote:
> >
> >
> > After finishing the guide, I open the hb launcher cia that has been
installed and then I get the above message until it finally errors out and
tells me to press start and exit. Any suggestions? Other CIA files loaded
and opened fine including the Luma Update cia.

**Comment by nickthegamer5** [comment]
You can try 5.4 and see if it works

**Comment by Sorrento6** [comment]
Is that a version of hb launcher?

**Comment by nickthegamer5** [comment]
I found out what's wrong, the website where the payload is hosted has gone down and no one will know when it's going to be back up. just wait a few days  and it should be up.

**Comment by Sorrento6** [comment]
Awesome. I thought I was losing my mind. Thanks for letting me know!

**Comment by nickthegamer5** [comment]
Ok it's backup try aging and tell me if it works

**Comment by Sorrento6** [comment]
Just tried it and it works like a charm.

**Comment by nickthegamer5** [comment]
Good the servers are backup :3

**Comment by Sorrento6** [comment]
Heck yeah! Thanks again.

**Comment by nickthegamer5** [comment]
NP enjoy your a9lh and I hope you don't brick :P

**Comment by Sorrento6** [comment]
@nickthegamer5 Have you heard anything about the initial Homebrew installation freezing up on a red screen this evening? Trying to set it up on my son's. He has a 10.3 and I've tried both browserhax and Ninjhax.

**Comment by Sorrento6** [comment]
NM! I was using an older starter pack. Goof.
