### ISSUE TITLE
Re-injecting/updating FBI post-a9lh

### ISSUE THREAD

**Issue by wrsg** [Plailect/Guide#209]
Not sure if you consider this worth adding, but could you explain the steps for updating FBI after doig a9lh if they aren't the same as they are when you first inject FBI into the H&S app.

**Comment by TheNain38** [comment]
@wsrg Most of the time, you will install `FBI.cia` using the injecting FBI, and then, use and update that one, instead of the injected one

**Comment by wrsg** [comment]
Sorry to ask here but how do I update the injected one correctly? I already tried using the FBI built-in updater and it created another app in the home menu

**Comment by ihaveamac** [comment]
best solution is to not keep it injected, instead install FBI.cia separately (using the updater did this), then fix health & safety. or else you'd have to keep re-injecting it each time there's an update which is annoying.

**Comment by wrsg** [comment]
> then fix health & safety
Could you please explain how I do that? I haven't been able to find an explanation other than redoing the steps in the guide (which would not make sense at this point in time since it involves a lot of effort of backing up and restoring nands etc)

**Comment by ihaveamac** [comment]
you can either

* install a H&S CIA depending on your model and region
* inject your hs.app

**Comment by nickthegamer5** [comment]
Why would you want to update the FBI in h&s when you can just install FBI.cia.
But anyway if you want to know how to inject the new FBI into h&s go here
 
https://gbatemp.net/threads/release-inject-any-app-into-health-safety-o3ds-n3ds-cfw-only.402236/

Also, when you click on the update button to check/install new updates it's going to install the FBI CIA because it cant inject its self into FBI so it's a bit pointless.(Other words it is going to install another FBI unless you already had it installed as a CIA)
