### ISSUE TITLE
Uncart no longer needed?

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#227]
Now that Decrypt9WIP can dump game carts as .3ds files in its latest stable release, the use of uncart can probably be removed from the guide. Hourglass9 could still be used for the initial installation steps, but then added/replaced with Decrypt9WIP at the end of Part 5, unless Hourglass9 adds the cartridge dumping feature at some point in the future.

**Comment by nickthegamer5** [comment]
Uncart can make stripped .3ds roms and normal roms(I don't know the difference) if decrypt9WIP can do that then there is no longer a need for uncart.

**Comment by jaxrogers2** [comment]
I think Decrypt9WIP can do both from my understanding sine in the release page (https://github.com/d0k3/Decrypt9WIP/releases/tag/20160626) says that the cartridge dumper includes "full/trimmed, with/without on the fly decryption" options so I assume that's what you are talking about when you say stripped vs normal .3ds rom dumps.

**Comment by Plailect** [comment]
I am waiting for this to be integrated into Hourglass9 (which @d0k3 seemed inclined to add when last we spoke about this).

**Comment by d0k3** [comment]
I've been thinking about adding the cartridge dumper to Hourglass9, but for now I decided that this is an 'advanced' feature rather than a 'novice' one (especially since there are four ways to dump a cart, and the user should get informed about the differences). I may add something to Hourglass9 at a later point, but not anytime soon. Still need to think about how to simplify it.

For those scared about D9's ability to overwrite an existing a9lh installation. I'm currently thinking about adding in extra safety, but I haven't decided yet how to do this. Maybe discuss this later, @Plailect ?

**Comment by ihaveamac** [comment]
> I'm currently thinking about adding in extra safety, but I haven't decided yet how to do this.

I've kind of had a few ideas but never got around to mentioning them. such as when "NAND Restore" is used, check for FIRM0 in NAND being corrupt, and if it is, notify/stop the user (maybe stop entirely, and tell them to use "forced" to bypass?). that would probably stop many accidental a9lh removals.

**Comment by d0k3** [comment]
That's actually not a bad idea at all, although I'd rather just check if a9lh is running at that point (a corrupted FIRM0 can mean different stuff, too). Take note that you can also overwrite your a9lh installation by injecting the FIRM0, FIRM1, sector0x96 and / or NAND header (and I don't want to add 'forced' versions to all of them). But, off-topic here - maybe discuss this in thread?
