### ISSUE TITLE
Add steps to restore original H&S app?

### ISSUE THREAD

**Issue by svanheulen** [Plailect/Guide#241]
I see many people in the FBI thread on GBATemp that seem to think they NEED to have FBI installed as H&S even after they're all complete and running A9LH. I understand the reason it's in the guide, since you have to format a few times and that keeps FBI from being lost. But it's not exactly ideal once you're on A9LH because you have to go through the dump/script/restore steps every single time you want to update it. Would it make sense to add steps to restore your original H&S and install the CIA version after you move your EmuNAND to SysNAND (part 5, section IV)? Or maybe at least make a note about it?

**Comment by svanheulen** [comment]
Actually part 5, section VI might be a better place for it.

**Comment by d0k3** [comment]
Tbh... we're talking about a cosmetic issue here. You can install FBI.cia from injected FBI just fine, then just ,move the injected icon out of the way so that you don't have two identical icons in your homemenu. If cosmetics are important for a user, he/she may also bring up the brainpower to notice he/she can just inject his dumped original hs.app back.

No need to clutter up the guide with this, my opinion. Leaving this open for now, just in case there are others.

**Comment by ihaveamac** [comment]
I don't really like keeping FBI injected into H&S. I feel users could get confused if they use FBI's update feature, and a new icon is added.

I guess the end could have the user install FBI.cia, but not need to remove the inject, just in case they accidentally delete the CIA-installed one or something.

**Comment by dark-samus** [comment]
idk, I think this is more than a cosmetic issue, as ihaveamac points out. I generally tend to simply reinstall the stock CIA for H&S, which is fairly easy. Tbh, there really isn't that much of a need to inject to H&S anymore, we could probably transition over to using it from the HBL after we boot up a CFW with sig patches

**Comment by svanheulen** [comment]
I agree that it is mostly a cosmetic issue for those that know what they're doing but not for everyone (probably a good chunk of the people using this guide). I brought it up because I have seen a lot of people posting in the FBI thread that are confused about why they have 2 FBI icons now. Or just asking how to update the H&S version because they think they need to use it that way.

**Comment by SirBeethoven** [comment]
Most People won't reinject back the regular Health and Safety just by thinking because they have to follow the guide to a T. 

Most people who don't know any of this but are seeing this for the first time will not risk their 3DS to go out of line of what the guide says. 

And this could cause problems later with the FBI update system. They wouldn't be able to fix it because they don't remember what's wrong. Then they'd try to fix it themselves, only to mess up something important.

I know a guy who couldn't get NTR to work, so he thought it would be a good idea to decrypt his NAND, delete firm 0 and firm 2 (yes he thought that's what Luma3DS meant), reincrypt it, and inject it. I was able to stop him as he was decrypting.

**Comment by Plailect** [comment]
Added.

**Comment by SirBeethoven** [comment]
Awesome! Thanks Plailect! Hope you had an awesome vacation by the way!
