### ISSUE TITLE
A newbie in trouble.

### ISSUE THREAD

**Issue by yellowaftertherain** [Plailect/Guide#248]
SO i followed the guide exactly to a T for installing and getting everything running smoothly on my N3DS that was NOOB and I wanted to get my NNID from an o3DS that hadnt been hacked (due to being upgraded to 11.0.33 before I cam acrossed this guide) and I did a system transfer from the old Ds to the New DS and now I no longer see FBI, or HBL or Luma3ds. just the home screen from my old 3ds, and all of the basic preloaded apps.

I am still able to get into Decrypt9, Luma3ds settings, EmuNAND9 through BOOT and button inputs, but I can no longer access FBI, or HBL or Luma3ds through the home menu. Is there a way to get back into them?

**Comment by nickthegamer5** [comment]
Inject FBI back into H&S and reinstall FBI.cia

On Jul 19, 2016, at 12:54 PM, yellowaftertherain <notifications@github.com<mailto:notifications@github.com>> wrote:


SO i followed the guide exactly to a T for installing and getting everything running smoothly on my N3DS that was NOOB and I wanted to get my NNID from an o3DS that hadnt been hacked (due to being upgraded to 11.0.33 before I cam acrossed this guide) and I did a system transfer from the old Ds to the New DS and now I no longer see FBI, or HBL or Luma3ds. just the home screen from my old 3ds, and all of the basic preloaded apps.

I am still able to get into Decrypt9, Luma3ds settings, EmuNAND9 through BOOT and button inputs, but I can no longer access FBI, or HBL or Luma3ds through the home menu. Is there a way to get back into them?

-
