### ISSUE TITLE
Adding a "Switch your console to dev." or add a link to https://github.com/maorninja/Follow-up-Guide/wiki

### ISSUE THREAD

**Issue by mariogamer2** [Plailect/Guide#254]
I do not know if it's useful since anyone can dev for nintendo...

**Comment by maorninja** [comment]
Did you simply read the sidebar? Might seem so. Let me tell you something:

We're simply getting dev **apps** for use with ShadowNAND. We are not switching our console to dev. Let me show you my prossess

Luma3DS->ShadowNAND->Downgrade->immediate Update->Home menu

For most of the users who will follow my guide, they would think that this is pointless (Downgrade and update). It works here because we're re-activating the ARM9 exploits that have been de-activated. But here, we aren't activating anything. We're downgrading and updating to get dev-apps. The dev apps in this way will install to NAND for sure and not make it either install to SD or Install FBI 1.x or have black apps.

I'm doing part 3 and after that, I'll ask plailect. Can you close this until tomorrow night/tonight?

**Comment by mariogamer2** [comment]
Ok thank
