### ISSUE TITLE
Stuck at Part 4 III 3. | OTPHelper not opening

### ISSUE THREAD

**Issue by veekdot** [Plailect/Guide#270]
As the title says: I'm stuck when I try to open the OTPHelper. I'm also a complete n00b, and this is the first 3DS I'm working with. It was a o3DS originally on 10.3, now the SysNAND is on 9.2 and the RedNand is on latest.

After quick flashing screens when opening OTPHelper, they remain black. Now after several tries I'm no longer able to do browserhax, the browser always returns a "communication error" Somehow the menuhax also got lost, I'm not sure wether its not installed anymore or the keybind got lost.

Also in Part5.II.2. I got a hs_emu.app instead of a hs.app, I renamed it, ran the go.bat script and still injected it with Decrypt9. In addition to that, when OTPHelper didn't want to start, I went and extracted everything from the OTPHelper zip in the root of the SD card, overwriting the launcher.dat. I think thats where something went wrong. I was strictly following the guide until Part4.SectionII. I still have the SD card backup from Part3.4.

**Comment by aroth-khashar** [comment]
Nothing in the OTPHelper zip file should have caused the problems you are experiencing. The arm9.bin and arm11.bin files needed to be on the root of the sd card in the first place, and the Launcher.dat, OTPHelper.bin, OTPHelper.dat and OTPHelper.nds files are for other methods of launching OTPHelper and should not have any impact by being present.

Sounds like maybe you either misread a step or have something else present on the sd card that should not be.

**Comment by maorninja** [comment]
Aren't you trying to open safe A9LH installer

On Jul 28, 2016, at 11:12 AM, aroth-khashar <notifications@github.com<mailto:notifications@github.com>> wrote:


Nothing in the OTPHelper zip file should have caused the problems you are experiencing. The arm9.bin and arm11.bin files needed to be on the root of the sd card in the first place, and the Launcher.dat, OTPHelper.bin, OTPHelper.dat and OTPHelper.nds files are for other methods of launching OTPHelper and should not have any impact by being present.

Sounds like maybe you either misread a step or have something else present on the sd card that should not be.

-

**Comment by aroth-khashar** [comment]
moarninja, if he is getting stuck on Part 4, then he has yet to downgrade and should not be messing with the A9LH installer yet. Files for it should not even be on his SD card during Part 4. If they are they might be where the problem is coming from.

**Comment by maorninja** [comment]
Before, the title said part 5. So I got confused on what part she's/he's in.

On Jul 28, 2016, at 11:17 AM, aroth-khashar <notifications@github.com<mailto:notifications@github.com>> wrote:


moarninja, if he is getting stuck on Part 4, then he has yet to downgrade and should not be messing with the A9LH installer yet. Files for it should not even be on his SD card during Part 4. If they are they might be where the problem is coming from.

-

**Comment by veekdot** [comment]
So, could there be a problem with me having renamed hs_emu.app to hs.app eg. simply using and later injecting a wrong file  and/or overwriting Launcher.dat? (something important in there that is not present in the new one from the OTPHelper zip)

I also noticed, and checked with friends on different ISPs that yls8.mtheall.com is either down or can't be reached from where I live, so theres the explanation why I can't use browserhax right now. I also tried using the google dns.

**Comment by veekdot** [comment]
Yeah, I've just tried through a VPN and I can now access the site on my desktop.

**Comment by aroth-khashar** [comment]
No, the file was named hs_emu.app because you selected the wrong name when dumping the file. It shouldn't cause the problem in question. Even if you happened to simply use the wrong file (from an old dump), it still shouldnt cause problems accessing OTPHelper or browserhax.

Unless you are using Launcher.dat to access the homebrew menu, that file shouldnt be affecting anything either. If you are following the guide 100% from the start (sounds like you are and started with an unhacked 9.3+ 3DS), you should not be using a Launcher.dat file at any step as far as I know. 

As for yls8.mtheall.com being down, I can access it just fine. What makes you say its down in your area? Are people trying to get a hit with a ping command in a linux terminal or windows command prompt? His server is set up to ignore ICMP ping requests (basically any "ping" command via a prompt or terminal), so getting "Request timed out." as a response to a ping is normal. Try actually loading the browserhax page in your desktop browser. [http://yls8.mtheall.com/3dsbrowserhax_auto.php](http://yls8.mtheall.com/3dsbrowserhax_auto.php) If you get a message about accessing it from a non-3DS browser then the site is online.

**Comment by veekdot** [comment]
I meant that several people in my area experience the same issue with yls8.mtheall.com being inaccessible from a desktop web browser. Seeing as the google dns also wouldn't work but a US vpn did (used tunnelbear), I assume it's a routing issue to our area. So, I guess I've got to put that on hold for now. But when I can eventually access yls8 again, would you reccomment starting over?

**Comment by aroth-khashar** [comment]
Honestly, if you haven't done anything beyond the initial downgrade to 9.2 then yes. I would start over at that step. In fact it sounds like maybe something went slightly sideways in that downgrade, so I would personally suggest going back to the start of Part 2 and attempting "downgrade" to 9.2 again. If memory serves, there were reports at one point of people having to run the downgrade 2 or 3 times before it completely properly (back when downgrading from 10.3 first became a thing). Someone may come along and correct me on this, but I am pretty sure the worst that can happen from trying to downgrade again if you really are on a proper 9.2 is that you waste a few minutes while sysupdater compares the title versions.

Quick question though, was this a completely unhacked 10.3 sysnand O3DS when you started the guide? Or was it one you had previously downgrade to 9.2 and installed CFW on that you are now deciding to set up with A9LH? Also, if its the later, what CFW were you using and what was the entry point for the cfw?

**Comment by veekdot** [comment]
It was a completely unhacked one. 

Thanks for the advice, I'll look into it later. I appreaciate your help ;)

**Comment by aroth-khashar** [comment]
No problem. Best advice I can offer is to read the guide in its entirety and familiarize yourself with each section before moving on. If time is an issue, the individual parts/pages make for great stopping points to set the system down and come back to it later when you have time. I would strongly suggest that for each of the Parts, you go over the sections/steps thoroughly before progressing, and take the time to reach each step as you perform it. If you follow the guide to the letter you should not encounter any problems.

Also if you are using Chrome as your browser, definitely get the AGE (arm9loaderhax guide enhancement) extension that is mentioned on the first page of the guide. Being able to effectively check off each step as you complete it really helps with keeping track of things. I think there is a version for Firefox as well.
