### ISSUE TITLE
Blank otp.bin for Cubic Ninja

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#293]
The guide says both to
1) create a blank otp.bin on the root of your SD card
2) copy a blank otp.bin to the root of your SD card

Obviously, these are not both necessary.

**Comment by blackalabi** [comment]
Nowhere in the guide does it say to "create" a blank otp.bin. The otp is one of the most crucial elements for this installation, and thus the reason for being told to **Copy your console specific OTP.bin from the /a9lh/ folder on your SD card to a safe location on your computer and back it up to multiple locations (such as online file storage)**. This is to ensure that if something were to happen either during installation process or afterwards, you wouldn't need to downgrade back to 2.1 in order to dump it yet again to use.

**Comment by arromdee** [comment]
> Nowhere in the guide does it say to "create" a blank otp.bin. 

https://github.com/Plailect/Guide/wiki/9.2.0-Update-%28Cubic-Ninja-OTP%29

2. **Create** a blank text file named otp.bin on the root of your SD card
...
6. Copy the 0 byte otp.bin file to the root of your SD card

**Comment by Plailect** [comment]
fixed
