### ISSUE TITLE
After the transfer the save is gone

### ISSUE THREAD

**Issue by Justinde75** [Plailect/Guide#324]
I did everyting exactly how it was in the guide, and after I transfered it onto the 3ds, when I start fieldrunners it just shows the scores.

**Comment by Plailect** [comment]
Did you select the option to transfer DSiWare?

**Comment by Justinde75** [comment]
Yeah, I checked everything twice. You should add that everyone should check if the save is on there before transfering

**Comment by nedron92** [comment]
I had nearly the same problem (but for me also the game was gone). 
But no problem, because if you do a backup of 3DS#1 Nand (best thing: with the games+saves installed), you can easily swap saves between 3DS#1 and 3DS#2 without problems (cause you have the same unique ID [Nintendo 3DS folder])
3DS#1: settings->dsiware->transfer game+save to sd-card
3DS#2: settings->dsiware->transfer game+save from sd-card to internal system itself

in fact, it's not a big problem if save and/or game is gone. (simply re-download on 3DS#2) and swap saves with the official backup-way of dsiware ;) 

Maybe @Plailect can mentioned it within the guide/troubeshooting. (also TODO a nand-backup of 3DS#1->non optional)

**Comment by Justinde75** [comment]
I backed up the emunand, but not the emunand I bought the game with.

**Comment by Justinde75** [comment]
I still have the account with 10 euros left on the #2 3ds

**Comment by nedron92** [comment]
Should be no problem..you could install a copy of the game(as a .cia ...) on the emunand, inject the hacked saves and then do the thing I mentioned above.

**Comment by Justinde75** [comment]
But why as a cia? Doesn't it only work on a legit version?

**Comment by nedron92** [comment]
The transfer itself only works with legit versions. ;)
But if you have done the transfer and restore 3DS#1 you can also install there the cia versions, inject the saves and backup with the official way and insert that backup to the system on 3DS#2. 
It works fine for me and I've have now a friends 3Ds on a9lh (was stock 11.0 before with the problem you had). 

So, in theory: 
You don't need to buy the game before the transfer - but have to buy at least after it, to download and install it. You can injecting the saves via the official backup-dsiware-to-sdCard way. (because if you restore 3DS#1 Nand you have the same ID within the Nintendo-3DS folder like 3DS#2 and the complete same structure, so its possible). 
Can @Plailect check this, if I'm right?

**Comment by Justinde75** [comment]
So, just that you know the #1 3ds is an o3ds and the #2 is a n3ds.

**Comment by Justinde75** [comment]
But I still don't really get it. Could you clean it up and and make it step by step please? I'm pretty through the wind today. I'm really sorry

**Comment by nedron92** [comment]
Don't know if O3DS and N3Ds will work, cause I had two O3DS's. 
Yes, wait:
0. Start the game on 3DS#2 first
1. Restore 3DS#1 (sys/emu)Nand which you have done the system-transfer
2. Search for the .cia-version of the game you bought
3. Install it on 3DS#1 (sys/emu)Nand which you have done the system-transfer
4. Inject the correct save of your game like it's mentioned in the guide itself (3DS#1)
5. Opening setting -> dsiware -> copy the game to sd (on 3DS#1)
6. Take out your sd-card from 3DS#1 and insert to 3DS#2
7. Opening setting -> dsiware -> copy game to system itself (on 3DS#2)
8. Try to launch the game on 3DS#2 and hopefully have the hacked save there

**Comment by Justinde75** [comment]
Well, I think I don't have the backed up nand from the one where I bought it. I just backed up the emunand where all the games were on. Maybe it made an auto backup but I am not really sure. I might have it somewhere.

**Comment by Justinde75** [comment]
It should work with o3ds and n3ds, since I don't need to transfer

**Comment by nedron92** [comment]
Doesn't matter I think, if you have a backup from the system you start the transfer on 3DS#1 it would work. (you can check the ID's within the 3DS folder on both sd-cards, there should be one that are equal on both)

**Comment by Justinde75** [comment]
So I should just look on the sd cards and the ID of the folders inside it?

**Comment by nedron92** [comment]
Yes. There should be a ID-folder that is on both sd-cards. This is the one you need. 
But don't know yet, how you can find out, which Nand has which ID. sorry. 
Try simply out with your backup emuNand you have^^.

**Comment by Justinde75** [comment]
I only have the emunand backup of the emunand that I used BEFORE I made another emunand to buy the dsiware game with. I don't know if that will work

**Comment by nedron92** [comment]
Maybe not no, sorry /: 
I used my normal emuNand for it, so that's the point.

**Comment by Justinde75** [comment]
Yeah, I am thinking of just doing it all over again. But I have to spend 15 euro again, and that sucks

**Comment by nedron92** [comment]
Yes that really sucks, sorry. 
But hopefully with that solution above we could help other people with the same problem.

**Comment by Justinde75** [comment]
Yeah, atleast that came out of this whole thing. I could transfer it back to a n3ds wait a week, and do it all again. But the problem is that I don't know anybody with a n3ds

**Comment by Justinde75** [comment]
But there is no homebrew app that can inject saves into a dsi ware game right?

**Comment by nedron92** [comment]
nope

**Comment by thyraxx** [comment]
Thanks nedron92, I had the same problem, and for me, your fix for just transferring the save from a CFW n3ds solved it.

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.

**Comment by nedron92** [comment]
It still applies to the new guide, because it depend on the DSiware downgrade/system transfer. 
Would be nice if you an check this. :)

**Comment by nedron92** [comment]
@Plailect it still applies to the new guide, because it belongs to the DSiWare Downgrade itself. 
It seems, that sometimes the system-transfer doesn't work correctly and leave you without the installed
games and/or saves. (also after swapping the sd-card etc.)
But if you do a sys/emuNand backup before on 3DS#1 (depend on the Nand you use for the system-transfer) you are save. Because if you restore this Nand (and the coressponding folder) on 3DS#1 you have the same 32-chara-id like 3DS#2 after the transfer. 
And this let you exchange the dsiware saves easily!

**Pre-Work:**
1.  If you do not have the game installed on 3DS#2 (after  transfer), link you NNID (you bought it with) to it and download again. 

**Steps:**
0. Install/Start the game on 3DS#2 first
1. Restore 3DS#1 (sys/emu)Nand which you have done the system-transfer
2. Inject the correct save of your game like it's mentioned in the guide itself (3DS#1)
3. Opening setting -> dsiware -> copy the game to sd (on 3DS#1)
4. Take out your sd-card from 3DS#1 and insert to 3DS#2
5. Opening setting -> dsiware -> copy game to system itself (on 3DS#2)
6. Try to launch the game on 3DS#2 and hopefully have the hacked save there

**Optional:** 
If you have no backup before the transfer itself..but a backup of it sometime ago:
1.0 Restore this Backup
1.1 Search for the .cia-version of the game you bought
1.2 Install it on 3DS#1 (sys/emu)Nand which you have done the system-transfer

**Comment by Plailect** [comment]
added
