### ISSUE TITLE
Downgrading Question

### ISSUE THREAD

**Issue by thatsmyface** [Plailect/Guide#328]
My buddy has a 3DS with CFW and we want to use the DSi method to downgrade my 3DS (on newest firmware) to 9.2. I have a lot of stuff on my 3DS that I want to keep (NNID, Games, Save Data, Themes, etc.). When we follow the process will I need to completely lose everything on my 3DS? Is there any way to get it back? Sorry for the noob question. Any help is greatly appreciated.

**Comment by Plailect** [comment]
Your games are linked to your NNID which you can sign back into, and you can backup your saves with [JKSM](https://github.com/J-D-K/JKSM/releases) by using browserhax on it.

**Comment by thatsmyface** [comment]
So just to clarify.. after we go through the process I can system transfer my DS back to his and then use my NNID on it mine and also still have CFW?

**Comment by Plailect** [comment]
Yes, but you have to wait a week to system transfer back to his. (remember though that you can't transfer from a new 3ds to an old 3ds)

**Comment by Blackwigg** [comment]
Sorry for respond on a old thread. But since you were already discutting it I didn't see why creating a new topic just to ask. How exactly can I sign back the 3ds 2# old NNID after doing all the three steps? If I remeber well it needs to format the system first to change the NNID back, but wouldn't that wipe all my data and the 3 steps I did in tutorial?
