### ISSUE TITLE
stuck on last part section II

### ISSUE THREAD

**Issue by R00t8ug** [Plailect/Guide#341]
Section II - Installing arm9loaderhax

Reinsert your SD card into your 2.1.0 3DS
Go to http://dukesrg.github.io/2xrsa.html?arm11.bin on your 3DS

I'm new 3ds, when i try unable to turn on my wifi, when i press internet setting it keep showing push the button which is old 3ds model... how? please advise.

**Comment by jaxrogers2** [comment]
With a new 3DS, you have to leave wifi on BEFORE you use OTPHelper to downgrade to 2.1 because 2.1 is old3DS firmware and as such you are not able to toggle wifi via the operating system whatsoever. The ONLY way to turn your wifi on in your case is to turn off your system, take off the back plate of your 3DS (like you were taking out the MicroSD card), find the battery, take it out, wait a couple of minutes, and then put it back in. This will reset the wifi to the default on setting and you will be able to proceed once you re-establish your internet connection settings after pulling the battery.

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
