### ISSUE TITLE
Error on Part 4, Section V, Step 10

### ISSUE THREAD

**Issue by Kered13** [Plailect/Guide#348]
Old 3DSXL, US, never homebrewed or anything else with this device before.

I've followed all the steps so far and everything has worked smoothly except for occasionally having to try Luma or menuhax twice before they work. I have all the backups from the various stages so far. I don't think it matters, but when I did the first format in Part 4, Section IV I set the country and other settings to whatever the first option was, because I knew I'd be formatting again. On the second format I used my normal settings.

When I try to downgrade to 2.1.0 it goes through it's whole thing, then ends with a line about NFIRM (no particular message, just some numbers), then goes to a black "An error has occurred" screen. OTPHelper's one click setup says that the downgrade failed.

I've tried five times now, every time it ends the same way. I even tried formatting one more time, in case I somehow messed one up. Still the exact same thing.

How can I get past this?

**Comment by willkof2** [comment]
Try this. Download this archive: http://www70.zippyshare.com/v/Fbj6n1vB/file.html extract, copy the firmware.bin from O3DS folder and paste inside luma folder in your SD card.

**Comment by Kered13** [comment]
This worked and I was able t finish the process, fantastic!

Could you explain at a high level what that did? I've really appreciated how this guide gives an overview of what each of the steps is doing. So I'm just curious to know what this did.

**Comment by willkof2** [comment]
If you had followed an old version of the guide, you would see a part of something like "download the corresponding firmware.bin to the model of your 3ds and place within the luma folder". This instruction was removed because according to Luma 3DS page https://github.com/AuroraWright/Luma3DS/wiki/Installation-and-Upgrade starting from version 5.0 the firmware.bin is no longer needed. I had the same problem as you and I could only solve by placing this file back into the luma folder. I'm sorry not to be able to explain why this worked :( maybe some luma random error, perhaps Plailect can clarify your question. Enjoy your cfw 3ds!

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
