### ISSUE TITLE
Use RedNAND instead of EmuNAND for steps 3 and 4

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#35]
Now that emuNAND9 in its latest release has full redNAND support, it might be better for the guide to give instructions on how to set up and use a redNAND for step 3 and step 4 (with the 2.1.0-4 downgrade) instead of emuNAND. This change might help resolve a few emuNAND specific problems with downgrading, and redNAND is definitely faster, especially on New 3DS. This change will probably require further testing before it is implemented, just to make sure that redNAND doesn't have any specific problems of its own with the current software used for emuNAND.

**Comment by Plailect** [comment]
Please read [the relevant wiki page](http://3dbrew.org/wiki/NAND_Redirection).

RedNAND and EmuNAND are very similar to each other and perform the same function. The ONLY difference between the two is how they are placed on the SD card, and their respective sizes.

Neither is "faster" than the other, and both are limited exclusively by SD class/speed.

With that said, I may switch to RedNAND for the *sole* reason that RedNAND always uses 1.2gb on New 3DS and 943mb on Old 3DS (regardless of the size of the internal chip since the larger chips are blank at the end anyways) which saves space in comparison to the 1.8gb and 954mb sizes that *some* New and Old 3DSs use, respectively.

**Comment by Plailect** [comment]
This has been added.
