### ISSUE TITLE
Warning about 2GB cards

### ISSUE THREAD

**Issue by quantumcat1** [Plailect/Guide#389]
There doesn't seem to be any warning to use a 4GB or higher SD card on Home, Part 1 or Part 2.

**Comment by Autz64** [comment]
SD cards higher than 4GB are not an issue, but SD cards higher than 32GB are not recommedable for these things, since they have to be formatted to FAT32. 

Also, for "better results", people should avoid using MicroSD's with adapters because the contact between the MicroSD and the Adapter and the 3DS can fail on some cases, and more if the MicroSD is old.

**Comment by Plailect** [comment]
2GB cards will work.

**Comment by quantumcat1** [comment]
Not if they have an emuNAND. Maybe have a warning to back up your emuNAND and format the card for no emuNAND prior to Part 2 (someone got stuck when they downgraded to 2.1 and couldn't make a backup)

**Comment by Autz64** [comment]
Not at all. What could be noted is that you need at least 1.8GB of free space to do this.
