### ISSUE TITLE
Inquiry - DSiWare Downgrade Process

### ISSUE THREAD

**Issue by Onoitsu2** [Plailect/Guide#414]
I was wondering if we could simply use TinyFormat to wipe out the NNID on Console #1 before doing the system transfer, almost like unlinking from EmuNAND. Never done a system transfer, but was a real thought to prevent having to transfer the device back from #2 to #1 again a week later, impatient kids where one has their device updated too much (11), and the other thankfully never had it on our WiFi so it was on 9.7 and downgraded beautifully after 2x formats just to make sure.

Also does the console push the DSiWare to the receiving console, or is it obtained from the store after the transfer has completed, only pulling in the save from the #1 device? Asking so I know if I need to keep it connected to WiFi after the transfer started, as power would not be an issue.

**Comment by jaxrogers2** [comment]
No, TinyFormat does not touch your NNID information, that's why it's used to unlink NANDs, so Tiny formatting console #1 wouldn't do anything except wipe your system.

In terms of the system transfer, if you are doing an old3ds to old3ds transfer, the DSiWare and its corresponding save data is transferred from console #1's NAND to console #1's SD card, and then (when prompted) you need to take the SD card out of console #1 and put it into console #2 to transfer the DSiWare. I'm not sure how this works on an old to new transfer, or even a new to new transfer, but I think new to new would be quite similar. So no, the DSiWare is not obtained from the eShop after the transfer- although you could do that, it would make the entire transfer pointless because the entire point of doing the system transfer is to transfer the hacked save, and a copy of one of the DSiWare games from the eShop wouldn't have the save.

**Comment by Onoitsu2** [comment]
I was using information pulled from https://www.reddit.com/r/3dshacks/comments/44uum6/psa_use_tinyformat_instead_of_formatting_through/

They talk about NNID being removed from the System when you use Tinyformat, so was simply curious. And thank you for answering how the DSiWare comes across. I simply thought it might work like an iCloud Restore might, for example the App Data is pulled from the "save" in this case the transfer where the title is actually pulled from the App Store, in this case the eStore.

**Comment by Onoitsu2** [comment]
Nevermind, i tried doing something a little different. I formatted the #1 console so its nnid was u linked and then restored the DSiWare to it, that I had backed up before. Thinking it would transfer without an nnid. Yeah does not work, sadly. Guess I will have to have the nnid there, redownload from eStore and transfer once more next week. Live and learn. Perhaps this can help with some more backstory on the process so nobody else has to wait another week like I must. Wife won't let me hardmod the one needing it to make things simple and no shops in town I can get it modded at behind her back. Oh well another week till kids get a ton of options.
