### ISSUE TITLE
Old 3DS to New 3ds Call nintendo

### ISSUE THREAD

**Issue by TypicalTorontoHipster** [Plailect/Guide#417]
Hey guys, one part of the 11.0 firmware/Dsiware guide suggests for us to call nintendo if our NNID doesn't work. I'm not entriely sure, but is this part a joke?  

Or, are we supposed to call and pretend that ihe NNID of the source 3ds  -in this case the O3ds -  was corrupted through regular system use?

**Comment by Margen67** [comment]
It's not a joke. You need to call them.
For some reason they don't let you unlink your NNID through their site.

**Comment by leo60228** [comment]
Call them and tell them you lost the system with the NNID (obviously don't tell them that it's hacked) and you want to transfer your NNID to your old system (the one you transferred from)

**Comment by TypicalTorontoHipster** [comment]
Let's say that I used an Old 3ds to downgrade a N3ds on firmware 11.0

Precisely which 3ds would I  need to say that I lost? The newly downgraded N3ds (target system), or the Old 3ds(source system)? And by doing this, will each system have its own NNID?

Sorry if I sound redundant, but I just want to be clear before moving forward. I've already lost 2 N3DS through attempting to downgrade. Don't wanna lose my O3DS too.

**Comment by jaxrogers2** [comment]
You don't necessarily need to tell them that you lost the console, because that is a lot more of a hassle to deal with. All you have to do is say that when you try to access the eShop/NNID settings that you get an error. Tell them that the error only happens when connected to wifi and that you performed a system transfer after formatting your console and using a different NNID. Then just ask to restore your original NNID. They will tell you press X+Y at the error screen, which will let you unlink the NNID from the system and then (through Nintendo Support's help) relink your NNID.

**Comment by TypicalTorontoHipster** [comment]
Ok thanks. I'm going to attempt the downgrade tonight. I'll keep you guys updated on how it goes.
