### ISSUE TITLE
Im still stck on sysdowngrader..

### ISSUE THREAD

**Issue by rexbuster** [Plailect/Guide#449]
![Uploading IMG_20160902_194543.jpg…]()
Im still on this error "Did not get am:u handle, please reboot" i know in guide said in could multiple times. But it almost 5 hours from the time i been doing this loop.Btw Im fw 10.4(11.0 from settings)(hardmod) O3ds xl. I read from some forum, to format my 3ds to make a downgrade. Should i format my 3ds? Or should continue this unlimited "Did not get am:u handle, please reboot" until miracle happens. Thank you..

**Comment by Ev1lbl0w** [comment]
"All variations of sysUpdater, not just sysDowngrader, have a very small chance of causing a "soft brick" once the downgrade is complete and the device reboots. This will cause the system to boot directly to the Nintendo error screen instructing users to power off the device.

The reason for this is unknown, but can be prevented by performing a system format before downgrading. It seems to happen very often on systems with ambassador status or who have DSiWare installed."

This is why you should format. And since you have a hardmod, do a NAND backup before formatting. Also try to inject the NFIRM again, maybe it failed.

**Comment by rexbuster** [comment]
I think the last part, injecting the NFRIM works.. I forgot to put the two cias in autofirm. Then followed the guide. Im on crypt9, But then the error now us on crypt9 that ctrnand transfer failed.. But btw Thanks.
