### ISSUE TITLE
How are you supposed to get into HBL to downgrade to 9.2 after a Fieldrunners downgrade?

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#497]
With 11.1 updating the home menu and making all exploits fail, how are you supposed to get into HBL to downgrade to 9.2 after performing a Fieldrunners downgrade? Does the NATIVE_FIRM downgrade allow HBL to boot from 10.7 payloads or what?

Also, will OoT3DDhax work for this if it is possible to get into HBL on 11.1 with the Fieldrunners downgrade? Since browserhax/menuhax are dead, that's really my only Homebrew access option for me besides installing steelhax and system transferring that along with Fieldrunners. If those work, what system version payload do I need to use for this then?

Lastly, a small 11.1 fix: Smilehax and all exploits relating to SmileBASIC no longer work due to a forced update (like Ironhax).

**Comment by mundaka0x** [comment]
im having that issue. i have system transfered from a 2ds with arm9 and field runners.
ive downgarded the native firm properly with the 11.1.0-34 files wich correspond to my system version. to make it short i using oothax with the 10.4.0-29U payload installed and have te correct boot.3dsx and 3ds folder respectively. it says the robpin payload is ready, but instead of flashing colors on the bottom screen it just says that an error has occured. ive tried this for the past hour. using different sd cards and different starter kits but same result. ihave done this method numerous times with other 3ds modles in 11.0.0-33U but this one will not boot up the hbl screen

**Comment by Ev1lbl0w** [comment]
Guys, update 11.1 rolled out only yesterday! Give time for @Plailect to see what changed and update the guide! He needs to wait for the homebrew developers (smea and/or yls8) to update the entrypoints. So please be patient!

**Comment by jaxrogers2** [comment]
Ev1lbl0w: That's what I figured, just had a friend with a New 3DS that wants to do Fieldrunners downgrade. It'll probably have to wait until 11.1 gets its own payload I guess.

**Comment by deew3e** [comment]
actually Plailect updated the downgrade-part for "11.1.0" 8 hours ago!

**Comment by jaxrogers2** [comment]
Yes, it mentions 11.1, and the Dsiware downgrade does work fine on 11.1, I understand that. It's really the HBL and 9.2 downgrade sections that are broken for 11.1 users right now.

**Comment by mundaka0x** [comment]
even though the guide says that it works on 11.1 supposedly thet native firm is on 10.4 so a oothax with a 10.4 payload should work. however it doesnt. i did evrything on the guide i wonder if a different boot.3dsx  is needed.

**Comment by deew3e** [comment]
with this you are fine: [,](https://twitter.com/smealum/status/775738645907054592) tested it.. works
