### ISSUE TITLE
Backup NAND?

### ISSUE THREAD

**Issue by Gelums** [Plailect/Guide#502]
Alright so today I purchased power saves and was able to get homebrew running on OOT my N3DS 10.7.0-32U since the browser was prompting me to update. Could I backup NAND before downgrade with homebrew channel? Or would I only be able to after getting arm9? Sorry I'm new to the 3ds homebrew stuff, I've only worked on Wii's.

**Comment by jaxrogers2** [comment]
You can only back up your console on system versions 9.0-9.2 unless you have A9LH already or a hardmod, so your 3DS has to make it through the 9.2 downgrade. If it doesn't and you softbrick, you have no other choice but to boot into recovery mode and update to 11.1 (or get a hardmod). Since formatting your console before attempting the downgrade reduces the chance of a softbrick, it is highly recommended that you do so.

**Comment by Gelums** [comment]
I don't have A9LH yet. I am using a fresh N3DS I got launch day. It's on 10.7.0-32U. how should I format? Through console? Should I format SD card too?

**Comment by iuzwpr2p39rh7w** [comment]
Of course you don't have A9LH yet, that's the whole point of this guide.

Format sysNAND:
`System Settings` > `Other Settings` > `4` > `Format System Memory`

Format SD card (from [this](https://github.com/Plailect/Guide/wiki/Home) page):
> If you need to format a brand new SD card, you can use [this](http://www.ridgecrop.demon.co.uk/index.htm?guiformat.htm) tool set to an Allocation Unit Size of 32K.

**Comment by Gelums** [comment]
I would format right now but it asks me if I am ready to connect to the internet to see if I am able to format.. I don't want it to automatically update after format or something lol

**Comment by Gelums** [comment]
I guess the only way is to go straight into downgrade because it wants to check nintendo ID before restore and to get to nintendo ID settings  I need to update

**Comment by Gelums** [comment]
Alright so I am on 9.2.0-20U now, now I could backup my Nand using homebrew or do I still need to install A9LH?
