### ISSUE TITLE
DSi Downgrade question

### ISSUE THREAD

**Issue by Kidel** [Plailect/Guide#526]
I'd like to restore its original NNID on 3DS#2 and my original NNID on 3DS#1 while keeping cfw. 
In order to do the first (original NNID on 3DS#2) I know the only way to change a NNID is to system format, but this will remove CFW, right?

So my plan is:
- Do the DSi Downgrade on 3DS#2
- **Format 3DS#2 while in downgraded firmware**
- Log back in with original NNID on 3DS#2
- Log back in with my NNID in 3DS#1
- _Restore NANDmin.bin on 3DS#1_ and dumped mii/miiplaza/extdata on 3DS#2 using browserhax/hb

My questions are: 
1) Will I still be able to continue the guide to the following steps on 3DS#2
2) Will 3DS#1 allow me to login and have the CFW?
3) **What does it mean** _"Go to the settings and attempt sign back into your initial NNID, then call Nintendo and ask about the error you get"_?
**What error should I get and what can Nintendo do about it?** 

Question 3 is what bugs me the most, it's very unclear ^^

Thanks.

**Comment by jaxrogers2** [comment]
Well first of all if you have A9LH system formatting won't remove CFW. Needless to say, the DSiWare downgrade is a whole lot less of a headache if 3DS #1 has an A9LH sysNAND.

1. It is not a good idea to format your console when you have just downgraded your firmware for the sake of linking a NNID. This is because if your 3DS softbricks and you are forced to update to 11.1, your Fieldrunners save is toast. Any restoring of the NNID on 3DS #2 should be once A9LH is installed on the console. Also a quick note: if you softbrick after the 9.2 downgrade, you will always softbrick until you perform a system format. I recommend trying the downgrade without formatting first. If you softbrick and you have to update back to 11.1, that's ok since you will still have Fieldrunners and the hacked save. Then, downgrade your firmware with the hacked save and then system format. Then, get into HBL and attempt the 9.2 downgrade again.

**Comment by Kidel** [comment]
Thanks. Then I guess I'll have to just wait a week or  "Go to the settings and attempt sign back into your initial NNID, then call Nintendo and ask about the error you get"

**Comment by jaxrogers2** [comment]
What kind of system transfer are you doing (old to old, old to new, new to new)?

**Comment by Kidel** [comment]
Simply new to new, so I can just transfer back after a week I guess. My only concern is with saved data, MIIs and MII Plaza games.

**Comment by jaxrogers2** [comment]
Yeah, your question about the calling Nintendo step doesn't apply to you, so don'5 worry about that. That is only if you are doing an old to new transfer or if you don't system transfer back for some reason.

**Comment by jaxrogers2** [comment]
Mii data is tied to your NNID. Mii Plaza data cannot be backed up in userland, so that will be lost when you systen format. However, once you have A9LH you are able to back up Mii Plaza savedata and then you can use a save editor program to customize your save to pretty much what it was before the format. I think streetpass data is actually tied to your NNID, so stuff like Find Mii progress and such is the only thing you lose. Also, if you have digital games, you need to back the saves for those up using JKSM through HBL because those will be lost in the format.
