### ISSUE TITLE
Suggestion: Add 3DSident to check NATIVE FIRM version

### ISSUE THREAD

**Issue by welintron** [Plailect/Guide#540]
After step 7 of Hardmod Downgrade guide you should add  this:
Use 3DSident, so it's possible to verify their native firm really was downgraded to 10.4.0 before proceed to downgrade to 9.2 on Sysdowngrader.

**Comment by Plailect** [comment]
Good idea, will add shortly

**Comment by Plailect** [comment]
Added.

**Comment by welintron** [comment]
Thank you!

**Comment by FLHCv2** [comment]
Plailect, to add to this, because the downgrade to 9.2 sometimes is a partial downgrade and can still say "Version 9.2" in the system settings, would using 3DSident verify that you are _in fact_ on a non-partially downgraded 9.2?  If so, I think adding to check 3DSident after the 9.2 downgrade would clear a lot of confusion behind partial downgrades.
