### ISSUE TITLE
CIA Solution fixed

### ISSUE THREAD

**Issue by correllroy** [Plailect/Guide#558]
Ok all fixed including game CIA i tried installing. I reinstalled my NAND.min,bin (keep A9LH) and made RedNAND EmuNAND and used TinyFormat to format my SysNAND and redid my microSDHC all booting up no problem. Turns out I never formatted my SysNAND. I read u suppose to format using TinyNAND ur SysNAND at least once. New Guide didnt have tht in instructions though. All working including bootNTR

Just letting know issue was resolved ^^

**Comment by sora10pls** [comment]
This guide doesn't require a system format unless you downgrade to 9.2, and even then it's not mandatory.

Your issue was FBI related (as shown in the pic below), and was already its own issue. Making this issue was also unnecessary, as you could've simply commented again on your previous issue...

![image](https://cloud.githubusercontent.com/assets/17801814/18819478/903e9daa-835f-11e6-8fa2-c043fcd97759.png)
