### ISSUE TITLE
Will doing this cause me to lose purchased content on 3DS #2?

### ISSUE THREAD

**Issue by jaytheidiot** [Plailect/Guide#590]
I have my Old 3DS with custom Firmware for my 3DS #1. On my New 3DS (3DS #2) with stock 11.1, I have purchased content from the Eshop including the Ambassador Certificate which cannot be purchased. By doing this, will I lose my Eshop content, or will I be better off waiting for an exploit to come about where I do not need to transfer data?

**Comment by CyHo** [comment]
i think you will lose all the download game in 3ds#2 because need to delete nnid before do system tansfer

**Comment by jaytheidiot** [comment]
Is there a way to restore my NNID? I saw some talk about calling Nintendo in some other posts. I'd rather not lose the games as there is some money invested in them.

**Comment by james-d-elliott** [comment]
To start with, NNID2 = current NNID on 3DS2, NNID1 is the one you make for the hack.

Alright, I have a bit of unique experience with this. When you do a system transfer you MERGE NNID's basically, i.e. NNID1 and NNID2 are associated with 3DS2, but you can only use one. The only way to get around this as far as I know is to transfer NNID2 off of 3DS2 first.

So, you can sys transfer from 3DS2 to 3DS1 first, buy the game, and a week later transfer back with the hack. 

Alternatively I believe (not specifically tested) you can do the following. Buy on NNID1 and transfer NNID1 to 3DS2, then 3DS2 has NNID1 and NNID2 associated with the serial. Once you've hacked 3DS2 you then sys format, which should allow you to relink NNID2 since the serial it is linked with is on 3DS2.

**Comment by jaytheidiot** [comment]
I did some searching and managed to find this https://gbatemp.net/threads/restore-original-nnid.443869/ 

The person claims they were able to re-download their games. I'm thinking I will give this a shot when I get home from work.

**Comment by Plailect** [comment]
Should work

**Comment by CyHo** [comment]
If let say like this, could i use one nnid to mod different console? because after i buy the fieldrunner, and do system transfer, i format that console after done then i reconnect to 3ds#1 again. It can be done?

**Comment by jaytheidiot** [comment]
What I did and it worked was transfer the 3DS1 with fieldrunners over to 3DS2 and installed homebrew. After that, I formated 3DS2 and logged in with my NNID that I originally used from 3DS2 and was able to redownload all my stuff. However, I lost 3DS1s NNID with the Fieldrunners. I assume if you waited a week and transfered 3DS1s NNID back to 3DS1, youd be able to bring back both the having the proper NNID, but I didn't care about losing a $5 game just to not have to wait a week.

**Comment by CyHo** [comment]
before that you just format your 3ds right, because i was think about no need buy the games everytime and i can just format the 3ds#2 after done inject FBI and put the nnid to 3ds#1, then i can re-download the game without buy again.
thanks for reply anyway

**Comment by jaytheidiot** [comment]
You could do that, but you would have to wait a week after transfering it to 3DS2 because of the wait they put on it. In my case, I was just impatient.

**Comment by james-d-elliott** [comment]
You cannot remove a single NNID from a device. When you SysTransfer it transfers ALL of the NNID's linked to that Serial. So if you try to transfer NNID1 to 3DS1 from 3DS2, NNID2 will be be on 3DS1 as well. It's better to just write it off.

**Comment by jaytheidiot** [comment]
Ahh, I was not aware of that.
