### ISSUE TITLE
Question-Suggestion RE: Recommending Downgrading to 9.2.0

### ISSUE THREAD

**Issue by Oscar256** [Plailect/Guide#618]
Hi,

My question/suggestion relates to Step 22 on https://github.com/Plailect/Guide/wiki/Homebrew-Launcher-(Browser).

"All versions above 9.2.0 should do 9.2.0 Downgrade at this point, before proceeding"

Could this be expanded on some to include advantages/disadvantages and why it's recommended? 

I'm on an o3DS with 9.9.0 w/ HBL set up and debating on whether I should downgrade and risk complicating things for myself since I do have some DSiware and a lot of DLC that I don't want to risk losing. Is it possible to continue without downgrading and what are the trade offs? 

Extra information would really help. Thanks in advance!

**Comment by Margen67** [comment]
Let me get this out of the way:
If you don't downgrade to 9.2 you can't install A9LH period.
This is due to there being no kernel exploits above 9.2.

Anyway..

Downgrade: Use a permanent entrypoint (A9LH) that allows instant bootup of CFW and homebrew but still lets you update. Best option.

Don't downgrade:
Be unable to use CFW completely. Also if you update (or don't) you have to deal with:
Entrypoints getting patched. So sometimes you might not even be able to use homebrew for a certain amount of time.
Since there's no CFW you can't boot HBL from the home menu.
You're limited to only "legit" CIAs which there aren't many of.
Frankenfirmware.(?)
Eshop, online games, etc not working.
No kernel so homebrew is MUCH more limited, and slower in some cases.
Without A9LH you won't be able to unbrick without using a hardmod.

That's all I can think of right now. There's probably other cons I didn't mention.

tl;dr downgrade to 9.2
