### ISSUE TITLE
sysDowngrader issues

### ISSUE THREAD

**Issue by Konng** [Plailect/Guide#687]
sysDowngrader sometimes fails on writing the first cia, leaving the console without a CVer, thus effectively excluding all 3ds game-based exploits(console can not launch 3ds carts(dont know about digital copies) as it triggers the version check on the cart, and attempting to use it to update crashes), breaking system settings, system updater, and safe_mode_firm.
This is a terrible problem and has happened to me and one other person so far(afaik). sysDowngrader also has no logs, which makes this problem even harder to debug. I really think PlaiSysUpdater should be used for the guide instead, as it doesnt have this problem, and has logs. Please consider this.

**Comment by Plailect** [comment]
This is a quirk of installing titles without actually booting into SAFE_MODE_FIRM, which is how [System Settings](https://3dbrew.org/wiki/System_Settings#System_Updater) does it. As far as I am aware this can happen on any kind of sysUpdater variant and can't really be fixed without figuring out a proper method for title installation. 

PlaiSysUpdater will not be used due to https://github.com/Plailect/PlaiSysUpdater/issues/10.
