### ISSUE TITLE
Backup NNID before system transfer ?

### ISSUE THREAD

**Issue by na-ji** [Plailect/Guide#700]
Hello !

I was wondering if it is possible to backup the linked NNID with Decrypt9 before the system transfer. Then injecting a blank NNID (still with Decrypt9), connecting with a fake account (the email verification does not seem to block anything) and finally doing the system transfer. It would be easier like that than waiting one week to system transfer back. The only downside of this would be that you would have to buy the DSi every time you create a new fake NNID. 
So is-it possible ?

Thanks !

**Comment by pbanj** [comment]
the nnid link is server side. logging it out/logging a new one in doesnt change the link status of the nnid that was orig on there that is why you still have to call even though you have a nand backup. even if you backed it up and injected a blank one when you did the system transfer the nnid would still get moved because it is linked server side.

**Comment by na-ji** [comment]
My bad, I forgot about the fact that the NNID is also synced server side.
Thanks for your answer !
