### ISSUE TITLE
Can't install menuhax on n3ds 9.9.0-26j.

### ISSUE THREAD

**Issue by gomi1992** [Plailect/Guide#713]
I have a n3ds 9.9.0-26j.
I followed the guide.
Download ropbin--N3DS_J_19456_9221.bin,size is 64k.
Do the prep work,Version check bypass.
Then i scan the qr code,launch the browser,and my n3ds bottom-screen colorfill always dead in gray color.
I got an error,then initialize the browser,try the exploit again,and I still get error.
I tried many times.
Could someone help me?

**Comment by the100guy** [comment]
try downloading the ropbin again?
I'm pretty sure that Browserhax and such can fail pretty often, the first time I did this it took me a good 15 or so tries on my N3DSXL. I think I deleted cookies first and then browser savedata (not sure if the order would matter or not) and then I put in the website manually instead of using the qr code.

**Comment by gomi1992** [comment]
Thx,I will try it later.
