### ISSUE TITLE
About TWN A9

### ISSUE THREAD

**Issue by david-zzj** [Plailect/Guide#734]
my old 3ds is 4.5T，never crack before.
yesterday i do the A9 myself，backup 4.5T，finished CTR 2.1J，and got the OTP.bin file
but when i restore 4.5T ，it  can‘t boot ，there is “ Fail to get the CTRNAND FIRM ” on the top screen.
i have  put the firmware.bin and cetk in the LUMA dir ，but it can’t boot also.
Please point a way for me，thank you！

**Comment by david-zzj** [comment]
can somebody tell me a way to try ？
thanks ！

**Comment by CrystalMoogle** [comment]
https://github.com/Plailect/Guide/issues/712
This issue has a similar problem, his solution was to delete firmware.bin and cetk and follow http://3ds.guide/9.2.0-ctrtransfer
Not sure if that will be the same for you though

**Comment by trbocode** [comment]
If you want to be on T reigon, you can reigon change back with the old way

**Comment by david-zzj** [comment]
thanks

**Comment by david-zzj** [comment]
If you want to be on T reigon, you can reigon change back with the old way

 the old way.......means？

**Comment by trbocode** [comment]
https://github.com/Plailect/Guide_RedNAND/wiki/Region-Changing
You will need the taiwan reigon CIA pack, search for "[MEGA] [CIA/BIN] MSET 4.X & 6.X backups, Browser backups, Update packs (All Regions)"
On step 27 you will need to change something in secureinfo, instead of 01 or 02 or 00 change to 06 for taiwan
