### ISSUE TITLE
Final step

### ISSUE THREAD

**Issue by Marika4Princess** [Plailect/Guide#791]
Hi guys, hopefully it is the last time I bother you,
I've used this guide to do a transfer: https://3ds.guide/dsiware-downgrade-(app-injection-and-second-3ds)

Now that the transfer is over, I do not know how to launch homebrew or anything. Ive clicked on ''sub wars'' but it says an error occurred and sends me back to the home page. 
Any leads? Thank you.

Marika

**Comment by Marika4Princess** [comment]
I've just realized ive done something wrong.. the section 4 with steelhax...
Starting at number 18... I didnt do the rest about the target n3ds... what should I do now? :(

**Comment by quantumcat1** [comment]
If Steeldiver gives you an error, that means that you didn't install it for the right version. If you installed it for version 11.2 but your target is 11.1 then you can try updating the target to see if it works then. Otherwise, you'll need another homebrew entrypoint (see Homebrew Launcher (No Browser)).

If Steeldiver isn't showing up at all, this could be because you used Tikshop in the past and you had a fake ticket, so the real one didn't transfer. In this case, just go into the eShop and download Steeldiver again. It'll give an error saying you don't need to redownload it, but then it will appear in your menu.

Hope this helps. In future, any problems you should ask on the GBATemp forums.

**Comment by Marika4Princess** [comment]
Thank you for your respond. My target is 11.2.0 - 35U, so I guess the update wont work.. And my source is an old3ds. You think my best option is to go No browser or to start the process all over again? Thank you for your help. And if you can send me the link to the best option I would appreciate it. I got lost alot during the process, especially that English isnt my first language X_X.

**Comment by nuimk** [comment]
If you choose wrong version during steelhax installation. And Steel Diver crashes after transfer. I think you still be able to access homebrew. See [troubleshooting](https://3ds.guide/troubleshooting), in section **After System Transfering steelhax, it crashes to a black screen on the target 3DS**

**Comment by Marika4Princess** [comment]
Thank you for trying... it seems like I still get the black screen. And then '' an error has occurred '' ... I guess I will redo the process again. Man I'm disappointed ... hopefully the same thing doesn't happen again.

**Comment by Marika4Princess** [comment]
What if I add the new bin in this file ? http://prntscr.com/dksn7q
