### ISSUE TITLE
Troubleshooting - Validation Failed; changing step 1 to "Restore your backup before proceeding".

### ISSUE THREAD

**Issue by Zufallszahl** [Plailect/Guide#84]
That first step should really be "Restore your RedNAND from emuNAND_formatted.bin". Rebooting to run Godmode9 doesn't seem to be safe, as I've seen several people report they bricked their consoles by doing that. 
Of course, I can't rule out user error since I wasn't standing behind their backs watching every step, but I still think it'd be safer to start with restoring the backup before proceeding. At the very least, it'll allow users to roll back to CFW+RedNAND without risking further A9LH installing attempts.

I am aware it does mention restoring RedNAND from backup further down, in the manual check part, but the majority of people with this problem will most likely ignore that part since OTPHelper isn't as prone to false positives as it used to be.

**Comment by Plailect** [comment]
Users should not even touch SysNAND with Godmode9 if they follow the steps, and restoring before continuing will not prevent them screwing something up after the restore.

Godmode9 is safe and will not brick you just by booting it.

**Comment by d0k3** [comment]
Seconding Plailect. GodMode9 really goes out of it's way not to touch anything critical unless you specifically tell it too. And telling it includes entering a five button sequence and a red top bar as warning. Also, restoring your EmuNAND does not do anything for your SysNAND, so it can't safe you from a brick.

Now, you say the brick happens while rebooting? Does that mean people can still enter their SysNAND and the brick happens when starting GM9? You also write about several people, which is rather strange, as the problem you describe sounds like a freak occurence.

If you want to help us find the cause behind this, provide us with the OTPHelper.logs of the bricked people. It is on their SD cards. Multiple OTPHelper.logs (from multiple people with the assumed same problem) will help.
