### ISSUE TITLE
Advise users who are skipping the NAND backup to back up tickets and saves

### ISSUE THREAD

**Issue by TheGag96** [Plailect/Guide#841]
It's not clear from the guide that ctrtransfers will delete tickets and saves from downloaded games and that restoring a NAND backup restores them too. There's steps to backup and restore tickets in the 9.2 ctrtransfer, but not in the 2.1 ctrtransfer (supposedly this was removed yesterday?). For those that are living on the edge for whatever reason, it would be nice to know this information. Thanks!

**Comment by lordscales91** [comment]
Oh! Thanks for this info! I got it clear now. So, basically at the current date, 6th of January of 2017, the 9.2.0-ctrtransfer has become just a troubleshooting guide for those who don't have a functional NAND backup. Therefore, the instructions to backup the installed tickets are only there. It's not on the 2.1.0-ctrtransfer because the guide clearly states that you need to make a backup before proceeding (and it's in bold). If you are not following the guide point per point you get what you deserve. It would be acceptable to place a warning like: "if you don't backup your NAND you will loose your installed titles", this surely will "enforce" somehow the users to make a backup of the NAND. Letting the users know that they can just skip that and backup just the titles is not necessary In My Humble Opinon

**Comment by Plailect** [comment]
The backup is not, and has never been, optional.

I'll extra bold this point in the guide, but I really don't understand the thought process of anyone who just skips the backup.

**Comment by TheGag96** [comment]
@lordscales91 Exactly. I understand going without a backup is pretty crazy (which is why I did it twice :^) ), but knowing what happens if you don't is important I think. 

The times I backed up were because the SD cards we were using were too small. You really do need something sizable depending on what you have installed - that information would also probably be helpful to know going in.
