### ISSUE TITLE
Jumping directly to arm9lh install if FW is 2.1.0 is correct?

### ISSUE THREAD

**Issue by lordscales91** [Plailect/Guide#953]
From here https://3ds.guide/get-started-(old-3ds) it is stated that if you have a functional browser and your version is 2.1.0 you can go directly to install arm9loaderhax, while this might be true the user will end up without a functional backup of his/her original FW. Is that intentional? I don't think so since the installation includes a system restore step.

I know that the odds of a user having his/her console still with version 2.1.0 are nearly zero. However, for completeness this should be fixed, which is another reason to create a separate step for the NAND backup as I suggested in #948

**Comment by Plailect** [comment]
There really is not much of a point to have a full NAND backup if no downgrades are involved. The only thing that is modified which could brick the device is the firm partitions (on n3ds the secret sector would need to be restored but nobody will already have a n3ds on 2.1.0), which have known contents and could therefore be fixed with a hardmod much in the way that [this](https://3ds.guide/hardmod-downgrade) works (i.e.: without a full NAND backup).
